Make it work with Stack (#144)
prettyprinter doesn't match on lts-9.0. You get the following error
with stack:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for dhall-1.6.0:
    prettyprinter-1.1 must match >=1.1.1 && <1.2 (latest applicable is 1.1.1)
needed since dhall-1.6.0 is a build target.
```