Make regression test #151 test the right thing (#1153)
From dhall/tests/Dhall/Test/Regression.hs:

    These two examples contain the following expression that loops
    infinitely if you normalize the expression before type-checking the
    expression:
    (λ(x : A) → x x) (λ(x : A) → x x)

The problem is typechecking that snipped already fails even before we
hit the self-application with the following error:
    Unbound variable: A

This is fixed by quantifying over `A`, resulting in the desired type
error:
    Error: Not a function
    1│                           x x