Fix compatibility with mmark 0.1 (#2822)
* Fix compatibility with mmark 0.1

PR #2802 allow mmark 0.1 but probably because of cached build deps, the
CI doesn't seem to catch the actual build failure:

```
 [ 2 of 10] Compiling Dhall.Docs.Markdown ( src/Dhall/Docs/Markdown.hs, dist/build/Dhall/Docs/Markdown.dyn_o )

 src/Dhall/Docs/Markdown.hs:33:5: error: [GHC-83865]
     • Couldn't match type: MMark -> Html ()
                      with: HtmlT Data.Functor.Identity.Identity ()
       Expected: MMark.RenderExtension -> Html ()
         Actual: MMark.RenderExtension -> MMark -> Html ()
     • Probable cause: ‘MMark.render’ is applied to too few arguments
       In the first argument of ‘(<$>)’, namely ‘MMark.render’
       In the expression: MMark.render <$> parseMarkdown relFile contents
       In an equation for ‘markdownToHtml’:
           markdownToHtml relFile contents
             = MMark.render <$> parseMarkdown relFile contents
    |
 33 |     MMark.render <$> parseMarkdown relFile contents
    |     ^^^^^^^^^^^^

 src/Dhall/Docs/Markdown.hs:33:22: error: [GHC-83865]
     • Couldn't match type ‘MMark’ with ‘MMark.RenderExtension’
       Expected: Either MarkdownParseError MMark.RenderExtension
         Actual: Either MarkdownParseError MMark
     • In the second argument of ‘(<$>)’, namely
         ‘parseMarkdown relFile contents’
       In the expression: MMark.render <$> parseMarkdown relFile contents
       In an equation for ‘markdownToHtml’:
           markdownToHtml relFile contents
             = MMark.render <$> parseMarkdown relFile contents
    |
 33 |     MMark.render <$> parseMarkdown relFile contents
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Let's fix it.

* Update all stack.yaml for mmark-0.1.0.0

* Retain compatibility with older mmark versions