set hPrint encodings to use utf8, independent of locale (#188)
On systems with the locale set to non-UTF8 (e.g. `LC_ALL=C`, the default POSIX
locale), handles are opened in that locale, so printing dhall’s error messages
fails on the first non-ASCII character:

```
Error: Not a function

Explanation: Expressions separated by whitespace denote function application,
like this:

    dhall: <stderr>: hPutChar: invalid argument (invalid character)
```

We set the stderr handle accordingly.

From the dhall.abnf specification:
; The character encoding for Dhall is UTF-8

How Haskell decodes input depends on the locale otherwise.