Require dhall 1.32.0+ for dhall-json 1.6.4 (#1779)
dhall-json 1.6.4 does not build with e.g. dhall 1.31.1:

```
[5 of 5] Compiling Dhall.JSONToDhall ( src/Dhall/JSONToDhall.hs, dist/build/Dhall/JSONToDhall.dyn_o )

src/Dhall/JSONToDhall.hs:793:45: error:
    Not in scope: ‘Lint.useToMap’
    Module ‘Dhall.Lint’ does not export ‘useToMap’.
    |
793 |     fmap (Optics.rewriteOf D.subExpressions Lint.useToMap) . loop (D.alphaNormalize (D.normalize expressionType))
    |                                             ^^^^^^^^^^^^^
```